### ISSUE TITLE
Proposal Description Hidden on Mobile

### ISSUE THREAD

**Issue by dternyak** [grant-project/grant-monorepo#107]
<img width="399" alt="screen shot 2018-09-25 at 3 31 09 pm" src="https://user-images.githubusercontent.com/7861465/46041310-11dd8800-c0d8-11e8-8c33-c93b7339cf5c.png">

**Comment by wbobeirne** [comment]
Aaah, great catch. If there's no sidebar, then the flex-grow height makes it zero. Should have considered that! Should be as simple as setting a min-height or flex-basis.

**Comment by wbobeirne** [comment]
While I'm in the neighborhood, the actions button should be tightened up here.
