### ISSUE TITLE
Backend Contract Syncing

### ISSUE THREAD

**Issue by dternyak** [grant-project/grant-monorepo#11]
- sync contract state to backend database
- implement websocket API to stream contract updates

**Comment by dternyak** [comment]
https://www.supermax.cool/

**Comment by dternyak** [comment]
Spec incoming.

**Comment by erikburt** [comment]
As you mentioned in the meeting Go and Node.js are definitely the preferred stacks to develop this in. However we will definitely need to organize some architecture stuff before we can make a choice there.
