### ISSUE TITLE
Profiles UI

### ISSUE THREAD

**Issue by dternyak** [grant-project/grant-monorepo#120]
With the introduction of user information being captured as part of the team flow (shown below), we'll want a view where users can directly see information about other users on Grant.io. We'll want to show all the data captured as part of this signup, at the least.

I'm looking for thoughts on if we should only have profiles for "identified" users, and not for users on which we technically have a user account, but haven't captured any additional data on. Right now this would be any non-team member user (e.g. a contributor).

Assuming that we show only information about identified users, we'll want to show the following: 

- Basic Profile info, same data shown in below screenshot.
- Proposals created (if any)
     - Title
     - Brief
     - Target/Funded
     - team members part of proposal, with links out to their profiles
- Proposals funded (if any)
- Proposals commented on (if any)

https://github.com/grant-project/grant-monorepo/pull/115

<img width="647" alt="screen shot 2018-09-27 at 10 47 52 am" src="https://user-images.githubusercontent.com/649992/46154217-a82dbd00-c242-11e8-933c-f2ba616c1180.png">

https://github.com/grant-project/grant-monorepo/pull/116 

<img width="327" alt="screen shot 2018-09-27 at 1 28 45 pm" src="https://user-images.githubusercontent.com/649992/46163448-49c00900-c259-11e8-8266-3759d3cea829.png">

**Comment by AMStrix** [comment]
Would it make sense to modify the existing Proposals view with a filter for user-creator, user-commented etc... ? Or is the purpose here a brief one-stop overview of a user's activity instead of the more bulky cards view?

**Comment by dternyak** [comment]
The purpose here is to hone in on what a specific user has done on the platform. 

For comparison, here is a similar view on the [Monero FFS](https://forum.getmonero.org/user/moneromooo). I think the FFS UI could use some improvement, but the same concept applies here.

It's basically a portal into the various ways the user has interacted with others on the site.

**Comment by wbobeirne** [comment]
Just for some inspiration, here are what a few other sites have going on for their profiles: https://imgur.com/a/JUHPvjQ
