### ISSUE TITLE
Immediately start bootstrapping web3

### ISSUE THREAD

**Issue by wbobeirne** [grant-project/grant-monorepo#122]
Currently web3 only begins to get fetched, and its accounts subsequently when you load a web3 enabled page. To reduce loading time, get logic out of components, and prevent re-running logic per component, we should immediately start doing this as soon as redux starts. This will also be a good place to auth a user from their stored credentials as soon as they land too. This may make the most sense as a saga.

**Comment by AMStrix** [comment]
100%! Drizzle might be helpful. [drizzle web3Saga](https://github.com/trufflesuite/drizzle/blob/master/src/web3/web3Saga.js)
