### ISSUE TITLE
Save create proposal form state

### ISSUE THREAD

**Issue by wbobeirne** [grant-project/grant-monorepo#13]
While working on a proposal, a lot could happen to interrupt you. What would be great is if we saved the state to local storage. While at some point we may want to implement a redux state local storage strategy, I think refactoring this whole component as it is right now to be redux-y might be overkill.

In the short term, we can save its state to local storage, and re-hydrate it on mount (And pop up a component letting them know we did that, with the option to restart it.)

Long term we'll want to look at server-side solutions for this, especially if we allow for collaborations.

**Comment by dternyak** [comment]
It may be wise to wait until https://github.com/grant-project/grant-monorepo/issues/40, as nextjs is special in the way it handles persisted data, and it will require re-work once we move off of it.
