### ISSUE TITLE
Mobile Styling Improvements

### ISSUE THREAD

**Issue by dternyak** [grant-project/grant-monorepo#135]
<img width="403" alt="screen shot 2018-10-03 at 9 44 24 pm" src="https://user-images.githubusercontent.com/7861465/46450165-8908c100-c755-11e8-8ae8-16c58a563368.png">

- [ ] Enlarge social media buttons
- [x] Fix collapsed proposal description

**Comment by wbobeirne** [comment]
Opinion: Mobile buttons should go below either the proposal, the campaign, or the team, and be 4 across instead. I think they're gonna be really crammed on the sides at mobile.
