### ISSUE TITLE
Convert all eth / wei numbers to BigNumber

### ISSUE THREAD

**Issue by wbobeirne** [grant-project/grant-monorepo#16]
Right now we've artificially limited everything to 10 ETH since that's what 32bit integers support, but we should start using `bn.js` wherever possible to future-proof. The frontend and the backend will simply communicate numbers as strings wherever is needed.

**Comment by HenryNguyen5** [comment]
Native BigInt support should be landing soon in TS 3.1:
https://github.com/Microsoft/TypeScript/issues/15096
https://github.com/Microsoft/TypeScript/pull/25886

**Comment by wbobeirne** [comment]
Siiick, though it'll be interesting to see if / how it interplays with Web3. That library might be stuck on bn.js.
