### ISSUE TITLE
Always Restoring Proposal State

### ISSUE THREAD

**Issue by dternyak** [grant-project/grant-monorepo#169]
<img width="877" alt="screen shot 2018-10-31 at 7 51 13 pm" src="https://user-images.githubusercontent.com/7861465/47811582-6236ae00-dd46-11e8-8225-862a7102aeff.png">

When creating a new proposal, the user is always prompted that their proposal has been restored, even when the proposal state is completely empty.

**Comment by wbobeirne** [comment]
That alert no longer exists as of #211.
