### ISSUE TITLE
Replace Styled Components with Less

### ISSUE THREAD

**Issue by dternyak** [grant-project/grant-monorepo#41]
We're currently implementing styles in a few different ways, including less, styled components, and inline styles. This should be consolidated to a single form, less.

- [ ] Investigate tslint flag for preventing inline styles
- [ ] Replace styled components in favor of basic less styles

**Comment by wbobeirne** [comment]
I personally have no issues with global styles, and find them to be the easiest to implement & debug (However I'll definitely acknowledge they are the most error-prone.) To keep the MyCrypto codebase tidy, we had a strict naming convention for styles that prevented collisions, and kept the resulting CSS pretty light: https://github.com/MyCryptoHQ/MyCrypto/wiki/Style-Guides#classnames Combined with the `classnames` module for composing classes with conditional modifiers.

However I'm also willing to admit I'm an old fart stuck in my ways. If modules are preferred, and there's a way to get them happy with TypeScript, I have no problem with going that route. I'd just like to see examples of how basic things would be done in this system (e.g. modifier classes, props becoming classes etc.)

**Comment by AMStrix** [comment]
SuiteCSS + classnames it is. The naming conventions should keep us out of trouble.
