### ISSUE TITLE
Cancel Campaign

### ISSUE THREAD

**Issue by dternyak** [grant-project/grant-monorepo#44]
As elaborated on in https://github.com/grant-project/grant-monorepo/pull/32#issuecomment-421221225, trustees are able to cancel crowdfunding campaigns at any point, including before the deadline for funding has completed.

We'll want to walk trustees through that flow, potentially in the Governance tab.

There are a few different states here where we should show different UIs:

1. Ongoing proposals
If a proposal is on-going, we won't need to show the refund voting progress bar and the milestone voting sections. It is not possible for these to have any non 0 values, as the crowdfund is still ongoing. However, we should show a single cancel button if they wish to cancel the campaign while it is on-going. 

2. Funded proposals
Proposals that are funded may have milestone payout requests and non-0 refund voting state. As such, we should make sure not to hide these from Trustees in the Governance tab, while continuing to provide them the ability to "cancel" the crowdfund even after it has been funded.

**Comment by wbobeirne** [comment]
Closed via #32.
