### ISSUE TITLE
Adjust Refund Progress Colors

### ISSUE THREAD

**Issue by dternyak** [grant-project/grant-monorepo#50]
![screen shot 2018-09-16 at 11 40 25 am](https://user-images.githubusercontent.com/7861465/45598667-5c0e8d00-b9a5-11e8-8758-f3cad5685ef8.png)

Green and red clash.

**Comment by wbobeirne** [comment]
Ugh, more inferred forced styles from Ant. Not sure if we can override this, but I'll give it a look.
