### ISSUE TITLE
Show Contributors to Proposal

### ISSUE THREAD

**Issue by dternyak** [grant-project/grant-monorepo#8]
To better understand who has contributed to a proposal and the amount of influence they have, we should a list of contributors (by address), and the amount they contributed to the proposal.

There are few options for where we can put this:

1. Expandable under campaign block.
2. In a tab

This will be further improved once we have rich profiles, where you can link to the address and see what other proposals they have contributed to.

- [ ] Update contract with getter to access contributor contribution state
- [ ] First-pass of UI showing contributors and their contribution amounts
- [ ] Finalized style pass

**Comment by wbobeirne** [comment]
My vote is for a tab. I think the only time we should show a top-level contributor is if / when we get grant funds backing projects.
